import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "./components/header";
import { roboto } from "./fonts";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log("roboto", roboto)
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}
