const DEFAULT_ANIMATION_TIMER = 1000;
const DEFAULT_ANIMATION = "ease-in-out";
const DEFAULT_CONTAINER_HEIGHT = "100vh";
const DEFAULT_CONTAINER_WIDTH = "100vw";
const DEFAULT_COMPONENT_INDEX = 0;
const DEFAULT_COMPONENTS_TO_RENDER_LENGTH = 0;

const DEFAULT_ANIMATION_TIMER_BUFFER = 200;
const KEY_UP = 38;
const KEY_DOWN = 40;
const MINIMAL_DELTA_Y_DIFFERENCE = 1;
const DISABLED_CLASS_NAME = "rps-scroll--disabled";

const TOUCHMOVE = "touchmove";
const KEYDOWN = "keydown";
const WHEEL = "wheel"

export {
    DEFAULT_ANIMATION_TIMER,
    DEFAULT_ANIMATION,
    DEFAULT_CONTAINER_HEIGHT,
    DEFAULT_CONTAINER_WIDTH,
    DEFAULT_COMPONENT_INDEX,
    DEFAULT_COMPONENTS_TO_RENDER_LENGTH,
    DEFAULT_ANIMATION_TIMER_BUFFER,
    KEY_UP,
    KEY_DOWN,
    MINIMAL_DELTA_Y_DIFFERENCE,
    DISABLED_CLASS_NAME,
    TOUCHMOVE,
    WHEEL,
    KEYDOWN
}